name: Docker Image CI to TestEnviroment

on:
  pull_request:
    types: [closed] 

jobs:
  build:
    if: ${{ github.event.pull_request.merged == true}}
    runs-on: ubuntu-latest

    env:
      TAG: pr-${{ github.event.pull_request.number }}

    steps:
      - uses: actions/checkout@v5

      - uses: docker/login-action@v3
        with:
          username: thenuker2
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            thenuker2/weatherforecast_api:latest
            thenuker2/weatherforecast_api:${{ env.TAG }}
