name: Docker Image CI

on:
  pull_request:
    types: [closed]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker tags
        id: vars
        run: |
          echo "TAG=pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build . \
            -t thenuker2/weatherforecast_api:${{ env.TAG }} \
            -t thenuker2/weatherforecast_api:latest \
            -f DockerAPITest/Dockerfile

      - name: Push Image to DockerHub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u thenuker2 --password-stdin
          docker push thenuker2/weatherforecast_api:${{ env.TAG }}
          docker push thenuker2/weatherforecast_api:latest
